# Site settings
title: SupervisorPHP
email: mark.sagikazar@gmail.com
description: SupervisorPHP website
baseurl: ""
url: "http://supervisorphp.com"
twitter_username: sagikazarmark
github_username:  sagikazarmark

exclude:
  - bower_components/
  - node_modules/
  - Gruntfile.js
  - README.md
  - bower.json
  - package.json

# Build settings
markdown: kramdown
